---
- hosts: all:!ad
  become: true
  become_method: sudo
  tasks:
    - include_vars:
        file: "{{ playbook_dir }}/../config/hmsidm-config.yaml"
        name: hmsidm_config

    - name: Configure env in /etc/ipa/hcc.conf
      ini_file:
        path: /etc/ipa/hcc.conf
        section: hcc
        option: environment
        value: "{{ hmsidm_config.rhc_env }}"

    - name: Configure mockapi in /ec/ipa/hcc.conf
      ini_file:
        path: /etc/ipa/hcc.conf
        section: hcc
        option: hcc_api_url
        value: "https://{{ hostvars[groups.ipaserver.0].meta_fqdn }}/mockapi"

- hosts: ipaserver
  become: true
  become_method: sudo
  tasks:
    - include_vars:
        file: "{{ playbook_dir }}/../config/hmsidm-config.yaml"
        name: hmsidm_config

    # See https://access.redhat.com/articles/3626371
    - name: Write Red Hat API offline token to /etc/ipa/hcc/refresh_token
      copy:
        dest: /etc/ipa/hcc/refresh_token
        content: "{{ hmsidm_config.rh_api_token }}"
        mode: '0640'
        owner: ipahcc
        group: root
