---
- hosts: ipaserver
  become: true
  become_method: sudo
  tasks:
    - include_vars:
        file: "{{ playbook_dir }}/../config/hmsidm-config.yaml"
        name: hmsidm_config

    - name: kinit as IPA admin
      shell: |
        echo Secret123 | kinit admin

    - name: ipa config-show
      command: "ipa config-show --raw"
      register: ipaconfig

    - name: Register domain
      when:
        - hmsidm_config.rhc_env in ['prod', 'stage']
        - meta_role == 'master'
        - "'hccdomainid' not in ipaconfig.stdout"
      block:
        - name: Run ipa-hcc token
          command: ipa-hcc token
          register: token

        - name: Run ipa-hcc register
          command: "timeout 30 ipa-hcc register --unattended {{ token.stdout | trim }}"

    - name: Add locations
      command: "ipa location-add {{ item }}"
      with_items:
        - sigma
        - tau
      register: result
      failed_when:
        - result.rc != 0
        - '"already exists" not in result.stderr'
      when: meta_role == 'master'

    - name: Add master server to location sigma
      command: "ipa server-mod {{ meta_fqdn }} --location=sigma"
      register: result
      failed_when:
        - result.rc != 0
        - '"no modifications to be performed" not in result.stderr'
      when: meta_role == 'master'

    - name: Add replicas to location tau
      command: "ipa server-mod {{ meta_fqdn }} --location=tau"
      register: result
      failed_when:
        - result.rc != 0
        - '"no modifications to be performed" not in result.stderr'
      when: meta_role == 'replica'

    - name: Enable mkhomedir on servers
      command: "authselect select sssd with-sudo with-mkhomedir"
