---
- hosts: ipaserver
  become: true
  become_method: sudo
  tasks:
    - name: Install ipa-hcc server plugin and registration service
      yum:
        name:
          - ipa-hcc-registration-service
          - ipa-hcc-server-plugin
        state: latest

- hosts: ipaclient
  become: true
  become_method: sudo
  tasks:
    - name: Install ipa-hcc client auto-enrollment service
      yum:
        name:
          - ipa-hcc-client-enrollment
        state: latest

- hosts: ipaserver:ipaclient
  become: true
  become_method: sudo
  tasks:
    - name: Gather the rpm package facts
      package_facts:
        manager: auto

    - name: List installed ipa-hcc packages version
      debug:
        msg: "{{ ansible_facts.packages[item] }}"
      with_items:
        - ipa-hcc-registration-service
        - ipa-hcc-server-plugin
        - ipa-hcc-client-enrollment
      when: item in ansible_facts.packages
