---
- hosts: ipaserver
  become: true
  become_method: sudo
  tasks:
    - name: Install ipa-hcc server plugin and registration service
      yum:
        name:
          - ipa-hcc-server
        state: latest
        update_cache: true

    - name: Install ipa-hcc mockapi
      yum:
        name:
          - ipa-hcc-mockapi
        state: latest
        update_cache: true
      when: mockapi is undefined or mockapi

    - name: Remove ipa-hcc mockapi
      yum:
        name:
          - ipa-hcc-mockapi
        state: absent
        update_cache: true
      when: mockapi is not undefined and not mockapi

- hosts: ipaclient
  become: true
  become_method: sudo
  tasks:
    - name: Install ipa-hcc client auto-enrollment service
      yum:
        name:
          - ipa-hcc-client
        state: latest
        update_cache: true

- hosts: ipaserver:ipaclient
  become: true
  become_method: sudo
  tasks:
    - name: Gather the rpm package facts
      package_facts:
        manager: auto

    - name: List installed ipa-hcc packages version
      debug:
        msg: "{{ ansible_facts.packages[item] }}"
      with_items:
        - ipa-hcc-server
        - ipa-hcc-client
      when: item in ansible_facts.packages
