- hosts: localhost
  gather_facts: False
  tasks:
    - include_vars:
        file: "{{ playbook_dir }}/../config/hmsidm-config.yaml"
        name: hmsidm_config

    - name: "Check for RHC_ENV"
      fail:
        msg: >
          Invalid or missing 'RHC_ENV' variable (got '{{ hmsidm_config.rhc_env }}').
          Did you forget to source 'idm-ci/secrets' file?
      when: 'hmsidm_config.rhc_env is not defined or hmsidm_config.rhc_env not in ["prod", "stage", "stage-mockapi", "ephemeral", "compose"]'

    - name: Check for expected RHC_ENV
      fail:
        msg: "The metadata file requires RHC_ENV to be set to one of '{{ expects_envs }}', got '{{ hmsidm_config.rhc_env }}'"
      when:
        - expects_envs is defined
        - hmsidm_config.rhc_env not in expects_envs

    - name: Check for RHC_ORG
      fail:
        msg: "The metadata file requires 'RHC_ORG' value."
      when:
        - not hmsidm_config.rhc_org
        - hmsidm_config.rhc_env in ['prod', 'stage', 'stage-mockapi']

    - name: Check for RHC_KEY
      fail:
        msg: "The metadata file requires 'RHC_KEY' value."
      when:
        - not hmsidm_config.rhc_key
        - hmsidm_config.rhc_env in ['prod', 'stage', 'stage-mockapi']
