---
- hosts: ipaclient
  become: true
  become_method: sudo
  tasks:
    - include_vars:
        file: "{{ playbook_dir }}/../config/hmsidm-config.yaml"
        name: hmsidm_config

    - name: Configure /etc/sysconfig/ipa-hcc-auto-enrollment
      template:
        src: ipa-hcc-auto-enrollment.j2
        dest: /etc/sysconfig/ipa-hcc-auto-enrollment

- hosts: ipaserver
  become: true
  become_method: sudo
  tasks:
    - include_vars:
        file: "{{ playbook_dir }}/../config/hmsidm-config.yaml"
        name: hmsidm_config

    - name: Configure /etc/ipa/hcc.conf
      template:
        src: hcc.conf.j2
        dest: /etc/ipa/hcc.conf

    # See https://access.redhat.com/articles/3626371
    - name: Write Red Hat API offline token to /etc/ipa/hcc/refresh_token
      copy:
        dest: /etc/ipa/hcc/refresh_token
        content: "{{ hmsidm_config.rh_api_token }}"
        mode: '0640'
        owner: ipahcc
        group: root

    - name: Restart HTTPD if running to reload /etc/ipa/hcc.conf
      command: systemctl try-restart httpd
