---
- hosts: ipaserver:ipaclient
  become: true
  become_method: sudo
  tasks:
    - include_vars:
        file: "{{ playbook_dir }}/../config/hmsidm-config.yaml"
        name: hmsidm_config

    - name: Check for RHEL 7 or newer
      fail:
        msg: HMSIDM / ipa-hcc is only supported on RHEL 7 or newer
      when: ansible_distribution != 'RedHat' or ansible_distribution_major_version < '8'

    - name: Install dnf copr command
      yum:
        name:
          - dnf-command(copr)
        state: latest

    - name: Enable ipa-hcc COPR repository with dnf copr
      shell: "dnf copr enable -y {{ hmsidm_config.ipa_hcc_copr }}"
