---
- hosts: ipaclient
  become: true
  become_method: sudo
  tasks:
    - name: Test ipa-hcc-auto-enrollment --upto register
      command: "/usr/libexec/ipa-hcc/ipa-hcc-auto-enrollment --insecure --hcc-api-host {{ item }} --upto register --override-server {{ item }}"
      loop: "{{ groups.ipaserver }}"
      register: out

    - name: "Show output"
      debug:
        msg: "{{ out }}"

    - name: Perform auto-enrollment
      command: "/usr/libexec/ipa-hcc/ipa-hcc-auto-enrollment --insecure --hcc-api-host {{ hostvars[groups.ipaserver.0].meta_fqdn }}"
      args:
        creates: /etc/ipa/default.conf

    - name: kinit admin
      shell: |
        echo "Secret123" | kinit admin

    - name: Show host record
      command: "ipa host-show {{ meta_fqdn }}"
      register: out

    - name: "Show output"
      debug:
        msg: "{{ out.stdout }}\n{{ out.stderr }}"

- hosts: ipaserver
  become: true
  become_method: sudo
  tasks:
    - name: Run ipa-hcc update
      command: ipa-hcc update
