---
- hosts: ipaserver
  become: true
  become_method: sudo
  tasks:
    - name: kinit as IPA admin
      shell: |
        echo Secret123 | kinit admin

    # replicas are missing correct forwarders
    - name: Fix DNS forwarders
      command: "ipa dnsserver-mod {{ meta_fqdn }} --forwarder=10.11.5.19"
      register: result
      failed_when:
        - result.rc != 0
        - '"no modifications to be performed" not in result.stderr'
