---
- hosts: ipaclient
  become: true
  become_method: sudo
  tasks:
    - name: Test ipa-hcc-auto-enrollment --upto register
      command: "/usr/libexec/ipa-hcc/ipa-hcc-auto-enrollment --verbose --insecure --idmsvc-api-url https://{{ item }}/api/idmsvc/v1 --upto register --override-ipa-server {{ item }}"
      loop: "{{ groups.ipaserver }}"
      register: out

    - name: "Show output"
      debug:
        msg: "{{ out }}"

    - name: Perform auto-enrollment
      command: "/usr/libexec/ipa-hcc/ipa-hcc-auto-enrollment --insecure --idmsvc-api-url https://{{ hostvars[groups.ipaserver.0].meta_fqdn }}/api/idmsvc/v1"
      args:
        creates: /etc/ipa/default.conf

    - name: kinit admin
      shell: |
        echo "Secret123" | kinit admin

    - name: Show host record
      command: "ipa host-show {{ meta_fqdn }}"
      register: out

    - name: "Show output"
      debug:
        msg: "{{ out.stdout }}\n{{ out.stderr }}"

- hosts: ipaserver
  become: true
  become_method: sudo
  vars:
    base_dir: "{{ playbook_dir | dirname | dirname }}"
    remote_dir: "/root/ipa-hcc"
  tasks:
    - name: Run ipa-hcc update
      command: ipa-hcc update

    - name: Copy integration test file
      copy:
        src: "{{ base_dir }}/tests/test_ipaserver_integration.py"
        dest: "{{ remote_dir }}/tests/"
        owner: root
        group: root
        mode: u+rwX,g+rX,o-rwx

    - name: Run integration tests
      command: python3 -m unittest -v tests/test_ipaserver_integration.py
      args:
        chdir: "{{ remote_dir }}"
      register: testresults

    - name: Print test results
      debug:
        msg: "stdout: {{ testresults.stdout | trim }}\nstderr: {{ testresults.stderr | trim }}"
