---
- hosts: all
  gather_facts: False
  tasks:
    - name: Make machines permanent
      command:
        openstack server set --name permanent-hmsidm-{{ meta_fqdn }} {{ meta_provider_id }}
      delegate_to: localhost
