---
- hosts: all
  gather_facts: False
  tasks:
    - name: Make machines permanent
      shell: |
        . ./config/openstack.rc.sh
        openstack server set --name permanent-hmsidm-{{ meta_fqdn }} {{ meta_provider_id }}
      args:
        chdir: "{{twd}}"
      delegate_to: localhost
