---
- hosts: all:!ad
  become: true
  become_method: sudo
  tasks:
    - include_vars:
        file: "{{ playbook_dir }}/../config/hmsidm-config.yaml"
        name: hmsidm_config

    - name: Register host with RHSM and connect to Insights (rhc connect)
      block:
        - name: Register host with RHC and subscription manager (RHEL 8+)
          shell: "rhc connect -o {{ hmsidm_config.rhc_org }} -a {{ hmsidm_config.rhc_key }}"
          args:
            # also creates /etc/pki/consumer/cert.pem
            creates: /var/lib/insights/host-details.json

        - name: Get subject of RHSM cert
          shell: "openssl x509 -subject -noout -in /etc/pki/consumer/cert.pem"
          register: rhsm_cert_content

        - name: Print subject of RHSM cert
          debug:
            msg: "RHSM cert: {{ rhsm_cert_content.stdout | trim }}"
      when: >
        ansible_distribution == 'RedHat' and ansible_distribution_major_version >= '8'
        and (target_group is undefined or meta_fqdn in groups[target_group])
