---
- hosts: all:!ad
  become: true
  become_method: sudo
  tasks:
    - name: Check for RHSM certificate
      stat:
        path: /etc/pki/consumer/cert.pem
      register: rhsm_cert

    - name: Check for Insights
      stat:
        path: /var/lib/insights/host-details.json
      register: insights_host
      when: rhsm_cert.stat.exists == true

    - name: Disconnect host from RHSM and RHC
      shell: "rhc disconnect"
      when: rhsm_cert.stat.exists == true
