---
- hosts: all:!ad
  become: true
  become_method: sudo
  tasks:
    - name: Register host with RHSM and connect to Insights (rhc connect)
      block:
        - include_vars:
            file: "{{ playbook_dir }}/../config/hmsidm-config.yaml"
            name: hmsidm_config

        - name: Install rhc and insights-client
          yum:
            name:
              - rhc
              - insights-client
            state: latest

        - name: Configure RHSM for stage environment
          shell: |
            subscription-manager config \
              --server.hostname subscription.rhsm.stage.redhat.com \
              --rhsm.baseurl https://cdn.stage.redhat.com
          when: hmsidm_config.rhc_env == 'stage'

        - name: Configure /etc/rhc/config.toml broker for stage environment
          lineinfile:
            path: /etc/rhc/config.toml
            regexp: '^broker\s*='
            line: 'broker = ["wss://connect.cloud.stage.redhat.com:443"]'
          when: hmsidm_config.rhc_env == 'stage'

        - name: Configure /etc/rhc/config.toml data-host for stage environment
          lineinfile:
            path: /etc/rhc/config.toml
            regexp: '^data-host\s*='
            line: 'data-host = "cert.cloud.stage.redhat.com"'
          when: hmsidm_config.rhc_env == 'stage'

        # required on 8.8 / 9.2
        - name: Configure /etc/insights-client/insights-client.conf base_url for stage environment
          ini_file:
            path: /etc/insights-client/insights-client.conf
            section: insights-client
            option: base_url
            value: "cert.console.stage.redhat.com"
            no_extra_spaces: true
            create: false
          when: hmsidm_config.rhc_env == 'stage'

        - name: Register host with RHC and subscription manager (RHEL 8+)
          when: ansible_distribution == 'RedHat' and ansible_distribution_major_version >= '8'
          block:
            - name: Run rhc connect (RHEL 8+)
              shell: "rhc connect -o {{ hmsidm_config.rhc_org }} -a {{ hmsidm_config.rhc_key }}"
              args:
                # also creates /etc/pki/consumer/cert.pem
                creates: /var/lib/insights/host-details.json

        - name: Register host with RHC and subscription manager (RHEL 7)
          when: ansible_distribution == 'RedHat' and ansible_distribution_major_version == '7'
          block:
            # "rhc connect" on RHEL 7 does not register and run insights-client
            - name: Run subscription-manager register (RHEL 7)
              shell: "subscription-manager register --org {{ hmsidm_config.rhc_org }} --activationkey {{ hmsidm_config.rhc_key }}"
              args:
                creates: /etc/pki/consumer/cert.pem

            - name: Run insights-client --register (RHEL 7)
              shell: "insights-client --register"
              args:
                creates: /var/lib/insights/host-details.json

            - name: Connect rhc (RHEL 7)
              shell: "rhc connect"

        - name: Get subject of RHSM cert
          shell: "openssl x509 -subject -noout -in /etc/pki/consumer/cert.pem"
          register: rhsm_cert_content

        - name: Print subject of RHSM cert
          debug:
            msg: "RHSM cert: {{ rhsm_cert_content.stdout | trim }}"
      when: >
        ansible_distribution == 'RedHat' and ansible_distribution_major_version >= '7'
        and (target_group is undefined or meta_fqdn in groups[target_group])
