---
- hosts: all:!ad
  become: true
  become_method: sudo
  tasks:
    - include_vars:
        file: "{{ playbook_dir }}/../config/hmsidm-config.yaml"
        name: hmsidm_config

    - name: Install rhc and insights-client
      yum:
        name:
          - rhc
          - insights-client
        state: latest
      when: >
        ansible_distribution == 'RedHat' and ansible_distribution_major_version >= '8'

    - name: Configure RHSM, insights-client, and rhc for Stage
      block:
        - name: Configure RHSM for stage environment
          shell: |
            subscription-manager config \
              --server.hostname subscription.rhsm.stage.redhat.com \
              --rhsm.baseurl https://cdn.stage.redhat.com

        # not strictly necessary, but we want to test these code paths
        - name: Configure RHSM for proxy squid.corp.redhat.com
          shell: |
            subscription-manager config \
              --server.proxy_scheme http \
              --server.proxy_hostname squid.corp.redhat.com \
              --server.proxy_port 3128
          when: false

        - name: Configure /etc/rhc/config.toml broker for stage environment
          lineinfile:
            path: /etc/rhc/config.toml
            regexp: '^broker\s*='
            line: 'broker = ["wss://connect.cloud.stage.redhat.com:443"]'

        - name: Configure /etc/rhc/config.toml data-host for stage environment
          lineinfile:
            path: /etc/rhc/config.toml
            regexp: '^data-host\s*='
            line: 'data-host = "cert.cloud.stage.redhat.com"'

        # required on 8.8 / 9.2
        - name: Configure /etc/insights-client/insights-client.conf base_url for stage environment
          ini_file:
            path: /etc/insights-client/insights-client.conf
            section: insights-client
            option: base_url
            value: "cert.console.stage.redhat.com"
            no_extra_spaces: true
            create: false
      when: >
        ansible_distribution == 'RedHat' and ansible_distribution_major_version >= '8'
        and hmsidm_config.rhc_env in ['stage', 'stage-mockapi']
