---
# current RHEL versions
srv92_c88_92:
  extends: .mr_template
  needs: ["rpms", "tox_check_f37", "tox_check_f38"]
  variables:
    METADATA_FILE_PATH: idm-ci/metadata/hmsidm-rhel92.yaml
    RHC_ENV: "stage"
    # uses RHC_ORG, RHC_KEY, RH_API_TOKEN settings
  except:
    variables:
      - $CI_MERGE_REQUEST_LABELS =~ /.*skip idm-ci.*/

# test with idm-domains-backend, does not use RHC
srv92_backend:
  extends: .mr_template
  needs: ["rpms", "tox_check_f37", "tox_check_f38"]
  variables:
    METADATA_FILE_PATH: idm-ci/metadata/hmsidm-rhel92-backend.yaml
    RHC_ENV: "compose"
  except:
    variables:
      - $CI_MERGE_REQUEST_LABELS =~ /.*skip idm-ci.*/
  # backend is currently not working
  allow_failure: true
