---
stages:
  - check
  - test

include:
  - remote: 'https://gitlab.cee.redhat.com/identity-management/idm-ci/-/raw/production/gitlab_template/qew.yml'
  - local: '.gitlab-idm-ci.yml'

tox_check:
  tags:
    - shared
  image: quay.io/tiran/ipa-hcc-ci:latest
  stage: check
  parallel:
    matrix:
      - TOXENV:
          - py,py27,py36
          - lint,format,bandit
          - jslint,yamllint,maketest
          - rpkg
  script:
    - tox -e $TOXENV
  only:
    - merge_requests
