[tool.black]
line-length = 78
target-version = ['py36']

[tool.coverage.run]
branch = true
relative_files = true
parallel = true
source = [
    "ipahcc_auto_enrollment",
    "ipahcc",
    "ipaserver",
    "tests",
]

[tool.coverage.paths]
source = [
   "ipahcc_auto_enrollment.py",
   "ipahcc/",
   "ipaserver/",
   "*.tox/*/lib*/python*/site-packages/ipahcc_auto_enrollment.py",
   "*.tox/*/lib*/python*/site-packages/ipahcc",
   "*.tox/*/lib*/python*/site-packages/ipaserver",
]
tests = [
   "tests/",
]

[tool.coverage.report]
exclude_lines = [
    "pragma: no cover",
    "if typing.TYPE_CHECKING",
    "if __name__ == .__main__.",
    "if False:",
]

[tool.mypy]
mypy_path = "stubs/"
explicit_package_bases = true

[[tool.mypy.overrides]]
module = [
    'augeas.*',
    'dbus.*',
    'gi.*',
]
ignore_missing_imports = true
