[tool.black]
line-length = 78
target-version = ['py36']

[tool.coverage.run]
branch = true
relative_files = true
parallel = true
source = [
    "ipahcc_auto_enrollment",
    "ipahcc",
    "ipaserver",
    "tests",
]

[tool.coverage.paths]
source = [
   "ipahcc_auto_enrollment.py",
   "ipahcc/",
   "ipaserver/",
   "*.tox/*/lib*/python*/site-packages/ipahcc_auto_enrollment.py",
   "*.tox/*/lib*/python*/site-packages/ipahcc",
   "*.tox/*/lib*/python*/site-packages/ipaserver",
]
tests = [
   "tests/",
]

[tool.coverage.report]
exclude_lines = [
    "pragma: no cover",
    "if typing.TYPE_CHECKING",
    "if __name__ == .__main__.",
    "if False:",
]

[tool.mypy]
mypy_path = "stubs/"
explicit_package_bases = true

[[tool.mypy.overrides]]
module = [
    'augeas.*',
    'dbus.*',
    'gi.*',
]
ignore_missing_imports = true

[tool.ruff]
select = [
    "E", "W", # pycodestyle
    "F", # pyflakes
    "I", # isort
    "B", # flake8-bugbear
    "S", # flake8-bandit
    "TCH", # flake8-type-checking
    "TID", # flake8-tide-imports
    "T10", # flake8-debugger
    "T20", # flake8-print
    "PL" # pylint
]
ignore = [
    "PLR0912", # Too many branches
    "PLR0913", # Too many arguments to function call
    "PLR2004", # Magic value used in comparison
    "PLR5501", # Consider using `elif`
    "S101", # Use of `assert` detected
    "F811", # Redefinition of unused {name} from line
]
# lowest supported version
target-version = "py37"

[tool.ruff.per-file-ignores]
# don't resort auto-generated stub files
"stubs/*" = ["I"]
# allow print in CLI scripts
"ipahcc/server/dbus_cli.py" = ["T20"]
"ipahcc_auto_enrollment.py" = ["T20"]

[tool.ruff.isort]
known-first-party = ["conftest"]
# forced-separate = [
#     "ipaclient", "ipalib", "ipapython", "ipaplatform", "ipaserver",
# ]
